# -*- coding: utf-8 -*-
"""Employee Productivity Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t4-7MKV85lBSovy_WFVdS_OkFHXDoa4e
"""

# Import Required Libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Plot Settings
plt.style.use('ggplot')
sns.set_theme(style="whitegrid")

print("Libraries Imported Successfully!")

# Load Dataset

df = pd.read_csv("/content/Employees Final Dataset.csv")

# Display first 5 rows
df.head()

print("Rows and Columns:", df.shape)

print(df.columns)

df.info()

df.describe()

missing = df.isnull().sum()
missing = missing[missing > 0]
print(missing)

print("Duplicate Records:", df.duplicated().sum())

# Remove duplicate records
df.drop_duplicates(inplace=True)

# Check dataset shape after removing duplicates
print("Dataset Shape:", df.shape)

# Verify duplicates again
print("Duplicate Records:", df.duplicated().sum())

df.sample(10)

df.dtypes

for column in df.columns:
    print("\n", column)
    print(df[column].unique())

df.info()

df.to_csv("Cleaned Employee Productivity Dataset.csv", index=False)

print("Cleaned Dataset Saved Successfully!")

# Create Age Groups

df['Age_Group'] = pd.cut(
    df['age'],
    bins=[20, 30, 40, 50, 60],
    labels=['21-30', '31-40', '41-50', '51-60']
)

df[['age', 'Age_Group']].head()

# Experience Level

df['Experience_Level'] = pd.cut(
    df['length_of_service'],
    bins=[0, 5, 10, 20, 40],
    labels=['Beginner', 'Intermediate', 'Experienced', 'Expert']
)

df[['length_of_service', 'Experience_Level']].head()

# Training Category

df['Training_Category'] = pd.cut(
    df['avg_training_score'],
    bins=[0, 50, 70, 85, 100],
    labels=['Low', 'Average', 'Good', 'Excellent']
)

df[['avg_training_score', 'Training_Category']].head()

# KPI Status

df['KPI_Status'] = df['KPIs_met_more_than_80'].map({
    1: 'Achieved',
    0: 'Not Achieved'
})

df[['KPIs_met_more_than_80', 'KPI_Status']].head()

# Award Status

df['Award_Status'] = df['awards_won'].map({
    1: 'Award Won',
    0: 'No Award'
})

df[['awards_won', 'Award_Status']].head()

# Performance Rating Category

df['Performance_Category'] = pd.cut(
    df['previous_year_rating'],
    bins=[0, 2, 3, 4, 5],
    labels=['Poor', 'Average', 'Good', 'Excellent']
)

df[['previous_year_rating', 'Performance_Category']].head()

# Check Newly Created Columns

df.columns

df.to_csv("Employee Productivity Feature Engineered.csv", index=False)

print("Feature Engineered Dataset Saved Successfully!")

# Chart 1: Employee Distribution by Department

plt.figure(figsize=(10,6))

sns.countplot(
    data=df,
    y='department',
    order=df['department'].value_counts().index,
    palette='viridis'
)

plt.title("Employee Distribution by Department", fontsize=16)
plt.xlabel("Number of Employees")
plt.ylabel("Department")

plt.tight_layout()

plt.savefig("Employee Distribution by Department.png", dpi=300)

plt.show()

# Chart 2: Employee Distribution by Region

plt.figure(figsize=(12,7))

sns.countplot(
    data=df,
    y='region',
    order=df['region'].value_counts().index,
    palette='coolwarm'
)

plt.title("Employee Distribution by Region", fontsize=16)
plt.xlabel("Number of Employees")
plt.ylabel("Region")

plt.tight_layout()

plt.savefig("Employee Distribution by Region.png", dpi=300)

plt.show()

# Chart 3: Gender Distribution

plt.figure(figsize=(6,6))

df['gender'].value_counts().plot(
    kind='pie',
    autopct='%1.1f%%',
    startangle=90
)

plt.title("Gender Distribution")

plt.ylabel("")

plt.tight_layout()

plt.savefig("Gender Distribution.png", dpi=300)

plt.show()

# Chart 4: Education Distribution

plt.figure(figsize=(8,6))

sns.countplot(
    data=df,
    x='education',
    palette='Set2'
)

plt.title("Education Distribution", fontsize=16)

plt.xticks(rotation=20)

plt.tight_layout()

plt.savefig("Education Distribution.png", dpi=300)

plt.show()

# Chart 5: Recruitment Channel Analysis

plt.figure(figsize=(8,6))

sns.countplot(
    data=df,
    x='recruitment_channel',
    palette='pastel'
)

plt.title("Recruitment Channel Analysis", fontsize=16)

plt.tight_layout()

plt.savefig("Recruitment Channel Analysis.png", dpi=300)

plt.show()

# Chart 6: Age Distribution

plt.figure(figsize=(8,6))

sns.histplot(
    df['age'],
    bins=20,
    kde=True,
    color='green'
)

plt.title("Age Distribution", fontsize=16)

plt.xlabel("Age")

plt.tight_layout()

plt.savefig("Age Distribution.png", dpi=300)

plt.show()

# Chart 7: Length of Service Distribution

plt.figure(figsize=(8,6))

sns.histplot(
    df['length_of_service'],
    bins=20,
    kde=True,
    color='orange'
)

plt.title("Length of Service Distribution", fontsize=16)

plt.xlabel("Years of Service")

plt.tight_layout()

plt.savefig("Length of Service Distribution.png", dpi=300)

plt.show()

# Chart 8: Average Training Score by Department

plt.figure(figsize=(12,6))

department_score = df.groupby('department')['avg_training_score'].mean().sort_values(ascending=False)

sns.barplot(
    x=department_score.values,
    y=department_score.index,
    palette='viridis'
)

plt.title("Average Training Score by Department", fontsize=16)
plt.xlabel("Average Training Score")
plt.ylabel("Department")

plt.tight_layout()

plt.savefig("Average Training Score by Department.png", dpi=300)

plt.show()

# Chart 9: Average Training Score by Education

plt.figure(figsize=(8,6))

education_score = df.groupby('education')['avg_training_score'].mean().sort_values(ascending=False)

sns.barplot(
    x=education_score.index,
    y=education_score.values,
    palette='Set2'
)

plt.title("Average Training Score by Education", fontsize=16)
plt.xlabel("Education")
plt.ylabel("Average Training Score")

plt.tight_layout()

plt.savefig("Average Training Score by Education.png", dpi=300)

plt.show()

# Chart 10: Previous Year Rating Distribution

plt.figure(figsize=(7,5))

sns.countplot(
    data=df,
    x='previous_year_rating',
    palette='coolwarm'
)

plt.title("Previous Year Rating Distribution", fontsize=16)
plt.xlabel("Previous Year Rating")
plt.ylabel("Number of Employees")

plt.tight_layout()

plt.savefig("Previous Year Rating Distribution.png", dpi=300)

plt.show()

# Chart 11: KPI Achievement Analysis

plt.figure(figsize=(6,6))

df['KPI_Status'].value_counts().plot(
    kind='pie',
    autopct='%1.1f%%',
    startangle=90
)

plt.title("KPI Achievement Analysis")

plt.ylabel("")

plt.tight_layout()

plt.savefig("KPI Achievement Analysis.png", dpi=300)

plt.show()

# Chart 12: Awards Won Analysis

plt.figure(figsize=(6,6))

df['Award_Status'].value_counts().plot(
    kind='pie',
    autopct='%1.1f%%',
    startangle=90
)

plt.title("Awards Won Analysis")

plt.ylabel("")

plt.tight_layout()

plt.savefig("Awards Won Analysis.png", dpi=300)

plt.show()

# Chart 13: Average Training Score by Gender

plt.figure(figsize=(6,5))

gender_score = df.groupby('gender')['avg_training_score'].mean()

sns.barplot(
    x=gender_score.index,
    y=gender_score.values,
    palette='pastel'
)

plt.title("Average Training Score by Gender", fontsize=16)
plt.xlabel("Gender")
plt.ylabel("Average Training Score")

plt.tight_layout()

plt.savefig("Average Training Score by Gender.png", dpi=300)

plt.show()

# Chart 14: Average Training Score by Age Group

plt.figure(figsize=(8,5))

age_score = df.groupby('Age_Group')['avg_training_score'].mean()

sns.barplot(
    x=age_score.index,
    y=age_score.values,
    palette='magma'
)

plt.title("Average Training Score by Age Group", fontsize=16)
plt.xlabel("Age Group")
plt.ylabel("Average Training Score")

plt.tight_layout()

plt.savefig("Average Training Score by Age Group.png", dpi=300)

plt.show()

# Chart 15: Correlation Heatmap

plt.figure(figsize=(10,8))

numeric_df = df.select_dtypes(include=['int64','float64'])

sns.heatmap(
    numeric_df.corr(),
    annot=True,
    cmap='coolwarm',
    fmt=".2f"
)

plt.title("Correlation Heatmap", fontsize=16)

plt.tight_layout()

plt.savefig("Correlation Heatmap.png", dpi=300)

plt.show()

# Chart 16: Training Score Distribution

plt.figure(figsize=(8,6))

sns.histplot(
    df['avg_training_score'],
    bins=20,
    kde=True,
    color='steelblue'
)

plt.title("Training Score Distribution", fontsize=16)

plt.xlabel("Training Score")

plt.tight_layout()

plt.savefig("Training Score Distribution.png", dpi=300)

plt.show()

# Chart 17: Length of Service Boxplot

plt.figure(figsize=(8,6))

sns.boxplot(
    x=df['length_of_service'],
    color='orange'
)

plt.title("Outliers in Length of Service", fontsize=16)

plt.tight_layout()

plt.savefig("Outliers in Length of Service.png", dpi=300)

plt.show()

# Chart 18: Average Training Score by Recruitment Channel

plt.figure(figsize=(8,6))

recruitment = df.groupby('recruitment_channel')['avg_training_score'].mean()

sns.barplot(
    x=recruitment.index,
    y=recruitment.values,
    palette='Set2'
)

plt.title("Average Training Score by Recruitment Channel", fontsize=16)

plt.ylabel("Average Training Score")

plt.tight_layout()

plt.savefig("Average Training Score by Recruitment Channel.png", dpi=300)

plt.show()

# Chart 19: Average Training Score by Experience Level

plt.figure(figsize=(8,6))

experience = df.groupby('Experience_Level')['avg_training_score'].mean()

sns.barplot(
    x=experience.index,
    y=experience.values,
    palette='viridis'
)

plt.title("Average Training Score by Experience Level", fontsize=16)

plt.ylabel("Average Training Score")

plt.tight_layout()

plt.savefig("Average Training Score by Experience Level.png", dpi=300)

plt.show()

# Chart 20: Top 10 Regions by Average Training Score

top_regions = (
    df.groupby('region')['avg_training_score']
      .mean()
      .sort_values(ascending=False)
      .head(10)
)

plt.figure(figsize=(10,6))

sns.barplot(
    x=top_regions.values,
    y=top_regions.index,
    palette='rocket'
)

plt.title("Top 10 Regions by Average Training Score", fontsize=16)

plt.tight_layout()

plt.savefig("Top 10 Regions by Average Training Score.png", dpi=300)

plt.show()

# Chart 21: Department-wise KPI Achievement

kpi = (
    df.groupby('department')['KPIs_met_more_than_80']
      .mean()
      .sort_values(ascending=False)
)

plt.figure(figsize=(10,6))

sns.barplot(
    x=kpi.values * 100,
    y=kpi.index,
    palette='mako'
)

plt.title("Department-wise KPI Achievement (%)", fontsize=16)

plt.xlabel("KPI Achievement (%)")

plt.tight_layout()

plt.savefig("Department-wise KPI Achievement.png", dpi=300)

plt.show()

# Chart 22: Top 10 Employees by Training Score

top_emp = (
    df.sort_values(by='avg_training_score', ascending=False)
      .head(10)
)

plt.figure(figsize=(12,6))

sns.barplot(
    x='employee_id',
    y='avg_training_score',
    data=top_emp,
    palette='flare'
)

plt.title("Top 10 Employees by Training Score", fontsize=16)

plt.xlabel("Employee ID")
plt.ylabel("Training Score")

plt.tight_layout()

plt.savefig("Top 10 Employees by Training Score.png", dpi=300)

plt.show()

# Total Employees

total_employees = len(df)

print("Total Employees:", total_employees)

# Average Training Score

avg_training = round(df['avg_training_score'].mean(), 2)

print("Average Training Score:", avg_training)

# Average Years of Service

avg_experience = round(df['length_of_service'].mean(), 2)

print("Average Years of Service:", avg_experience)

# Average Employee Age

avg_age = round(df['age'].mean(), 2)

print("Average Age:", avg_age)

# KPI Achievement Percentage

kpi_rate = round(
    (df['KPIs_met_more_than_80'].sum() / total_employees) * 100,
    2
)

print("KPI Achievement Rate:", kpi_rate, "%")

# Award Winning Percentage

award_rate = round(
    (df['awards_won'].sum() / total_employees) * 100,
    2
)

print("Award Winning Rate:", award_rate, "%")

# Previous Year Rating

avg_rating = round(df['previous_year_rating'].mean(),2)

print("Average Previous Year Rating:", avg_rating)

# Department with Highest Average Training Score

top_department = (
    df.groupby('department')['avg_training_score']
      .mean()
      .idxmax()
)

top_department_score = (
    df.groupby('department')['avg_training_score']
      .mean()
      .max()
)

print("Top Department:", top_department)
print("Average Training Score:", round(top_department_score,2))

# Region with Highest Training Score

top_region = (
    df.groupby('region')['avg_training_score']
      .mean()
      .idxmax()
)

top_region_score = (
    df.groupby('region')['avg_training_score']
      .mean()
      .max()
)

print("Top Region:", top_region)
print("Average Training Score:", round(top_region_score,2))

print(top_region)
print(top_region_score)

# Highest Training Score

highest_score = df['avg_training_score'].max()

print("Highest Training Score:", highest_score)

df.columns

# KPI Summary Table

kpi_summary = pd.DataFrame({

    "KPI":[

        "Total Employees",
        "Average Age",
        "Average Experience",
        "Average Training Score",
        "Average Previous Year Rating",
        "KPI Achievement Rate (%)",
        "Award Winning Rate (%)",
        "Top Performing Department",
        "Top Performing Region",
        "Highest Training Score"

    ],

    "Value":[

        total_employees,
        avg_age,
        avg_experience,
        avg_training,
        avg_rating,
        kpi_rate,
        award_rate,
        top_department,
        top_region,
        highest_score

    ]

})

kpi_summary

# Save KPI Summary

kpi_summary.to_csv("Employee_Productivity_KPI_Summary.csv",index=False)

print("KPI Summary Saved Successfully!")

# KPI Dashboard

plt.figure(figsize=(12,6))

sns.barplot(
    data=kpi_summary.iloc[1:7],
    x='Value',
    y='KPI',
    palette='viridis'
)

plt.title("Employee Productivity KPI Dashboard",fontsize=16)

plt.tight_layout()

plt.savefig("Employee Productivity KPI Dashboard.png",dpi=300)

plt.show()